# Generated by Django 5.2.1 on 2026-01-30 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_coursetopicmodel_coursemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopicmodel',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_topic_images/'),
        ),
    ]
