# Generated by Django 5.2.1 on 2026-01-30 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coursetopicmodel_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursetopicmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
