# Generated by Django 5.2.1 on 2026-01-30 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_coursetopicmodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='topics',
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='topics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.coursetopicmodel'),
        ),
    ]
