# Generated by Django 5.2.1 on 2026-01-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_coursemodel_topics_coursemodel_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20),
        ),
    ]
