# Generated by Django 5.2.1 on 2026-01-30 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_coursemodel_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='enrollment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='learning_outcomes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
