# Generated by Django 5.2.1 on 2026-01-30 03:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_coursemodel_enrollment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LecturerModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='lecturer_images/')),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('about', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lecturers',
            },
        ),
        migrations.AddField(
            model_name='coursemodel',
            name='lecturers',
            field=models.ManyToManyField(blank=True, related_name='courses', to='core.lecturermodel'),
        ),
    ]
