# Generated by Django 5.2.1 on 2026-01-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_lecturermodel_coursemodel_lecturers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursemodel',
            old_name='topics',
            new_name='topic',
        ),
    ]
