# Generated by Django 5.2.1 on 2026-01-30 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_topics_coursemodel_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='coursetopicmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lecturermodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='rolemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
