# Generated by Django 5.2.1 on 2026-01-30 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_coursemodel_slug_alter_coursetopicmodel_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
