# Generated by Django 5.2.1 on 2026-01-30 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_coursemodel_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
