# Generated by Django 5.2.1 on 2026-01-30 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_coursemodel_access_duration_days_paymentmethodmodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmodel',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
