# Generated by Django 5.2.1 on 2026-01-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_enrollmodel_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethodmodel',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_methods/'),
        ),
    ]
