# Generated by Django 5.2.1 on 2026-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paymentmethodmodel_featured_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lessonmodel',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
