# Generated by Django 5.2.1 on 2026-01-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_enrollmodel_status_alter_lessonmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
