# Generated by Django 5.2.1 on 2026-01-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_lessonmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
