# Generated by Django 5.2.1 on 2026-01-30 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_lessonmodel_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonmodel',
            name='duration',
            field=models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True),
        ),
    ]
