# Generated by Django 5.2.1 on 2026-01-30 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_lessonmodel_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonmodel',
            name='duration',
        ),
    ]
