# Generated by Django 6.0 on 2026-02-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_blogcategorymodel_blogmodel_contactmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
