# Generated by Django 6.0.2 on 2026-02-24 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_partnermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnermodel',
            name='slug',
        ),
    ]
