# Generated by Django 6.0.2 on 2026-02-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_donationmodel_delete_donationformmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='program',
            field=models.ManyToManyField(related_name='donations', to='core.programmodel'),
        ),
    ]
