# Generated by Django 6.0.2 on 2026-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_languagemodel_textkeymodel_translationmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationmodel',
            name='status',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='yes', max_length=20),
        ),
    ]
