# Generated by Django 6.0.2 on 2026-03-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_alter_donationmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnermodel',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
