# Generated by Django 6.0.2 on 2026-03-12 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_partnermodel_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
