# Generated by Django 6.0.2 on 2026-03-14 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_volunteermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteermodel',
            name='rating',
        ),
    ]
