# Generated by Django 6.0.2 on 2026-03-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_remove_volunteermodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermodel',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='volunteermodel',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
