# Generated by Django 6.0.2 on 2026-03-19 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_volunteermodel_email_volunteermodel_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturermodel',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonmodel',
            name='video_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
