# Generated by Django 6.0.2 on 2026-03-21 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_lecturermodel_video_url_lessonmodel_video_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcategorymodel',
            options={'verbose_name': 'Blog Category', 'verbose_name_plural': 'Blog Categories'},
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name': 'Blog', 'verbose_name_plural': 'Blogs'},
        ),
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='coursemodel',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursetopicmodel',
            options={'verbose_name': 'Course Topic', 'verbose_name_plural': 'Course Topics'},
        ),
        migrations.AlterModelOptions(
            name='donationmodel',
            options={'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='enrollmodel',
            options={'verbose_name': 'Enrollment', 'verbose_name_plural': 'Enrollments'},
        ),
        migrations.AlterModelOptions(
            name='filemodel',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='languagemodel',
            options={'verbose_name': 'Language', 'verbose_name_plural': 'Languages'},
        ),
        migrations.AlterModelOptions(
            name='lecturermodel',
            options={'verbose_name': 'Lecturer', 'verbose_name_plural': 'Lecturers'},
        ),
        migrations.AlterModelOptions(
            name='lessonmodel',
            options={'verbose_name': 'Lesson', 'verbose_name_plural': 'Lessons'},
        ),
        migrations.AlterModelOptions(
            name='lessonprogressmodel',
            options={'verbose_name': 'Lesson Progress', 'verbose_name_plural': 'Lesson Progresses'},
        ),
        migrations.AlterModelOptions(
            name='partnermodel',
            options={'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethodmodel',
            options={'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AlterModelOptions(
            name='programmodel',
            options={'verbose_name': 'Program', 'verbose_name_plural': 'Programs'},
        ),
        migrations.AlterModelOptions(
            name='rolemodel',
            options={'verbose_name': 'Role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='sectionmodel',
            options={'verbose_name': 'Section', 'verbose_name_plural': 'Sections'},
        ),
        migrations.AlterModelOptions(
            name='sitemodel',
            options={'verbose_name': 'Site', 'verbose_name_plural': 'Sites'},
        ),
        migrations.AlterModelOptions(
            name='textkeymodel',
            options={'verbose_name': 'Text Key', 'verbose_name_plural': 'Text Keys'},
        ),
        migrations.AlterModelOptions(
            name='translationmodel',
            options={'verbose_name': 'Translation', 'verbose_name_plural': 'Translations'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='volunteermodel',
            options={'verbose_name': 'Volunteer', 'verbose_name_plural': 'Volunteers'},
        ),
    ]
