# Generated by Django 6.0.2 on 2026-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_hometextmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitemodel',
            name='slug',
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='logo',
            field=models.ImageField(null=True, upload_to='logo'),
        ),
    ]
