# Generated by Django 6.0.2 on 2026-04-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_sitemodel_slug_sitemodel_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='set_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
