# Generated by Django 6.0.2 on 2026-04-26 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_blogmodel_set_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='currency',
            field=models.CharField(choices=[('euro', 'Euro'), ('mmk', 'MMK')], default='euro', max_length=30),
        ),
    ]
