# Generated by Django 6.0.2 on 2026-04-26 08:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_coursemodel_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonmodel',
            name='is_seen',
            field=models.ManyToManyField(related_name='seen_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
