# Generated by Django 6.0.2 on 2026-05-14 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_lessonmodel_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='hour',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
